slight rewrite of explanation of _ underscore protection
ietf-wg-dance/draft-dance-architecture pull request #64
Opened 2024-08-15 18:19 UTC by mcr

close #59

2024-08-15 18:33 UTC, oej requested changes

2024-08-15 18:33 UTC, oej commented on draft-ietf-dance-architecture.md
> +The underscore is not a valid character for in names used in the Web PKI.
"for in names" - maybe remove the "in"

2024-08-21 15:34 UTC, mcr commented on draft-ietf-dance-architecture.md
> +The underscore is not a valid character for in names used in the Web PKI.
```suggestion
The underscore is not a valid character for names used in the Web PKI.
```

2024-08-21 15:36 UTC, oej approved these changes
ok

2024-08-21 15:38 UTC, mcr commented on draft-ietf-dance-architecture.md
> +The naming pattern suggested in {{I-D.ietf-dane-client-certs}} includes
```suggestion
The naming pattern suggested in {{I-D.ietf-dane-client-auth}} includes
```

2024-08-21 15:40 UTC, merged